.PHONY: run build build_dev run_sass build_css

build:
	npm run build
run:
	npm run dev
build_dev:
	npm run build-dev
run_sass:
	sass --watch ../sass/app.sass:app/styles.css
build_css:
	sass ../sass/app.sass:app/styles.css