"""
 # Copyright (c) 06 2015 | surya
 # 22/06/15 nanang.ask@kubuskotak.com
 # This program is free software; you can redistribute it and/or
 # modify it under the terms of the GNU General Public License
 # as published by the Free Software Foundation; either version 2
 # of the License, or (at your option) any later version.
 #
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 #  test_init_lang.py
"""
from niimanga.models import DBSession
from niimanga.models.master import ISOLang
from niimanga.tests import TestDBBase


class InitLang(TestDBBase):
    def test_normal(self):
        ini_db = [
            {'name': 'English', 'iso': 'en'},
            {'name': 'Afar', 'iso': 'aa'},
            {'name': 'Abkhazian', 'iso': 'ab'},
            {'name': 'Afrikaans', 'iso': 'af'},
            {'name': 'Amharic', 'iso': 'am'},
            {'name': 'Arabic', 'iso': 'ar'},
            {'name': 'Assamese', 'iso': 'as'},
            {'name': 'Aymara', 'iso': 'ay'},
            {'name': 'Azerbaijani', 'iso': 'az'},
            {'name': 'Bashkir', 'iso': 'ba'},
            {'name': 'Byelorussian', 'iso': 'be'},
            {'name': 'Bulgarian', 'iso': 'bg'},
            {'name': 'Bihari', 'iso': 'bh'},
            {'name': 'Bislama', 'iso': 'bi'},
            {'name': 'Bengali/Bangla', 'iso': 'bn'},
            {'name': 'Tibetan', 'iso': 'bo'},
            {'name': 'Breton', 'iso': 'br'},
            {'name': 'Catalan', 'iso': 'ca'},
            {'name': 'Corsican', 'iso': 'co'},
            {'name': 'Czech', 'iso': 'cs'},
            {'name': 'Welsh', 'iso': 'cy'},
            {'name': 'Danish', 'iso': 'da'},
            {'name': 'German', 'iso': 'de'},
            {'name': 'Bhutani', 'iso': 'dz'},
            {'name': 'Greek', 'iso': 'el'},
            {'name': 'Esperanto', 'iso': 'eo'},
            {'name': 'Spanish', 'iso': 'es'},
            {'name': 'Estonian', 'iso': 'et'},
            {'name': 'Basque', 'iso': 'eu'},
            {'name': 'Persian', 'iso': 'fa'},
            {'name': 'Finnish', 'iso': 'fi'},
            {'name': 'Fiji', 'iso': 'fj'},
            {'name': 'Faeroese', 'iso': 'fo'},
            {'name': 'French', 'iso': 'fr'},
            {'name': 'Frisian', 'iso': 'fy'},
            {'name': 'Irish', 'iso': 'ga'},
            {'name': 'Scots/Gaelic', 'iso': 'gd'},
            {'name': 'Galician', 'iso': 'gl'},
            {'name': 'Guarani', 'iso': 'gn'},
            {'name': 'Gujarati', 'iso': 'gu'},
            {'name': 'Hausa', 'iso': 'ha'},
            {'name': 'Hindi', 'iso': 'hi'},
            {'name': 'Croatian', 'iso': 'hr'},
            {'name': 'Hungarian', 'iso': 'hu'},
            {'name': 'Armenian', 'iso': 'hy'},
            {'name': 'Interlingua', 'iso': 'ia'},
            {'name': 'Interlingue', 'iso': 'ie'},
            {'name': 'Inupiak', 'iso': 'ik'},
            {'name': 'Indonesian', 'iso': 'in'},
            {'name': 'Icelandic', 'iso': 'is'},
            {'name': 'Italian', 'iso': 'it'},
            {'name': 'Hebrew', 'iso': 'iw'},
            {'name': 'Japanese', 'iso': 'ja'},
            {'name': 'Yiddish', 'iso': 'ji'},
            {'name': 'Javanese', 'iso': 'jw'},
            {'name': 'Georgian', 'iso': 'ka'},
            {'name': 'Kazakh', 'iso': 'kk'},
            {'name': 'Greenlandic', 'iso': 'kl'},
            {'name': 'Cambodian', 'iso': 'km'},
            {'name': 'Kannada', 'iso': 'kn'},
            {'name': 'Korean', 'iso': 'ko'},
            {'name': 'Kashmiri', 'iso': 'ks'},
            {'name': 'Kurdish', 'iso': 'ku'},
            {'name': 'Kirghiz', 'iso': 'ky'},
            {'name': 'Latin', 'iso': 'la'},
            {'name': 'Lingala', 'iso': 'ln'},
            {'name': 'Laothian', 'iso': 'lo'},
            {'name': 'Lithuanian', 'iso': 'lt'},
            {'name': 'Latvian/Lettish', 'iso': 'lv'},
            {'name': 'Malagasy', 'iso': 'mg'},
            {'name': 'Maori', 'iso': 'mi'},
            {'name': 'Macedonian', 'iso': 'mk'},
            {'name': 'Malayalam', 'iso': 'ml'},
            {'name': 'Mongolian', 'iso': 'mn'},
            {'name': 'Moldavian', 'iso': 'mo'},
            {'name': 'Marathi', 'iso': 'mr'},
            {'name': 'Malay', 'iso': 'ms'},
            {'name': 'Maltese', 'iso': 'mt'},
            {'name': 'Burmese', 'iso': 'my'},
            {'name': 'Nauru', 'iso': 'na'},
            {'name': 'Nepali', 'iso': 'ne'},
            {'name': 'Dutch', 'iso': 'nl'},
            {'name': 'Norwegian', 'iso': 'no'},
            {'name': 'Occitan', 'iso': 'oc'},
            {'name': '(Afan)/Oromoor/Oriya', 'iso': 'om'},
            {'name': 'Punjabi', 'iso': 'pa'},
            {'name': 'Polish', 'iso': 'pl'},
            {'name': 'Pashto/Pushto', 'iso': 'ps'},
            {'name': 'Portuguese', 'iso': 'pt'},
            {'name': 'Quechua', 'iso': 'qu'},
            {'name': 'Rhaeto-Romance', 'iso': 'rm'},
            {'name': 'Kirundi', 'iso': 'rn'},
            {'name': 'Romanian', 'iso': 'ro'},
            {'name': 'Russian', 'iso': 'ru'},
            {'name': 'Kinyarwanda', 'iso': 'rw'},
            {'name': 'Sanskrit', 'iso': 'sa'},
            {'name': 'Sindhi', 'iso': 'sd'},
            {'name': 'Sangro', 'iso': 'sg'},
            {'name': 'Serbo-Croatian', 'iso': 'sh'},
            {'name': 'Singhalese', 'iso': 'si'},
            {'name': 'Slovak', 'iso': 'sk'},
            {'name': 'Slovenian', 'iso': 'sl'},
            {'name': 'Samoan', 'iso': 'sm'},
            {'name': 'Shona', 'iso': 'sn'},
            {'name': 'Somali', 'iso': 'so'},
            {'name': 'Albanian', 'iso': 'sq'},
            {'name': 'Serbian', 'iso': 'sr'},
            {'name': 'Siswati', 'iso': 'ss'},
            {'name': 'Sesotho', 'iso': 'st'},
            {'name': 'Sundanese', 'iso': 'su'},
            {'name': 'Swedish', 'iso': 'sv'},
            {'name': 'Swahili', 'iso': 'sw'},
            {'name': 'Tamil', 'iso': 'ta'},
            {'name': 'Tegulu', 'iso': 'te'},
            {'name': 'Tajik', 'iso': 'tg'},
            {'name': 'Thai', 'iso': 'th'},
            {'name': 'Tigrinya', 'iso': 'ti'},
            {'name': 'Turkmen', 'iso': 'tk'},
            {'name': 'Tagalog', 'iso': 'tl'},
            {'name': 'Setswana', 'iso': 'tn'},
            {'name': 'Tonga', 'iso': 'to'},
            {'name': 'Turkish', 'iso': 'tr'},
            {'name': 'Tsonga', 'iso': 'ts'},
            {'name': 'Tatar', 'iso': 'tt'},
            {'name': 'Twi', 'iso': 'tw'},
            {'name': 'Ukrainian', 'iso': 'uk'},
            {'name': 'Urdu', 'iso': 'ur'},
            {'name': 'Uzbek', 'iso': 'uz'},
            {'name': 'Vietnamese', 'iso': 'vi'},
            {'name': 'Volapuk', 'iso': 'vo'},
            {'name': 'Wolof', 'iso': 'wo'},
            {'name': 'Xhosa', 'iso': 'xh'},
            {'name': 'Yoruba', 'iso': 'yo'},
            {'name': 'Chinese', 'iso': 'zh'},
            {'name': 'Zulu', 'iso': 'zu'},
            ]

        for lang in ini_db:
            lang = ISOLang(lang['name'], lang['iso'])
            lang.save_it()
