"""rev_db_29062015

Revision ID: 1298b037320c
Revises: 
Create Date: 2015-06-29 00:37:38.655165

"""

# revision identifiers, used by Alembic.
revision = '1298b037320c'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_artist',
    sa.Column('slug', sa.Unicode(length=200), nullable=True),
    sa.Column('id', sa.CHAR(length=10), nullable=False),
    sa.Column('artist_name', sa.Unicode(length=100), nullable=True),
    sa.Column('artist_ability', sa.CHAR(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_artist')),
    sa.UniqueConstraint('slug', name=op.f('uq_tb_artist_slug'))
    )
    op.create_table('tb_author',
    sa.Column('slug', sa.Unicode(length=200), nullable=True),
    sa.Column('id', sa.CHAR(length=10), nullable=False),
    sa.Column('author_name', sa.Unicode(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_author')),
    sa.UniqueConstraint('slug', name=op.f('uq_tb_author_slug'))
    )
    op.create_table('tb_character',
    sa.Column('slug', sa.Unicode(length=200), nullable=True),
    sa.Column('id', sa.CHAR(length=10), nullable=False),
    sa.Column('character_name', sa.Unicode(length=100), nullable=True),
    sa.Column('character_rules', sa.Unicode(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_character')),
    sa.UniqueConstraint('slug', name=op.f('uq_tb_character_slug'))
    )
    op.create_table('tb_genre',
    sa.Column('slug', sa.Unicode(length=200), nullable=True),
    sa.Column('id', sa.CHAR(length=10), nullable=False),
    sa.Column('genre_name', sa.Unicode(length=100), nullable=True),
    sa.Column('genre_desc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_genre')),
    sa.UniqueConstraint('slug', name=op.f('uq_tb_genre_slug'))
    )
    op.create_table('tb_grp',
    sa.Column('id', sa.CHAR(length=10), nullable=False),
    sa.Column('grp_name', sa.Unicode(length=45), nullable=True),
    sa.Column('grp_slug', sa.Unicode(length=45), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_grp'))
    )
    op.create_table('tb_lang',
    sa.Column('id', sa.CHAR(length=10), nullable=False),
    sa.Column('name', sa.Unicode(length=50), nullable=True),
    sa.Column('iso', sa.CHAR(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_lang'))
    )
    op.create_table('tb_manga',
    sa.Column('slug', sa.Unicode(length=200), nullable=True),
    sa.Column('id', sa.CHAR(length=10), nullable=False),
    sa.Column('thumb', sa.Unicode(length=255), nullable=True),
    sa.Column('manga_title', sa.Unicode(length=255), nullable=True),
    sa.Column('manga_title_aka', sa.Text(), nullable=True),
    sa.Column('manga_desc', sa.Text(), nullable=True),
    sa.Column('status', sa.SMALLINT(), nullable=True),
    sa.Column('category', sa.CHAR(length=2), nullable=True),
    sa.Column('type', sa.CHAR(length=2), nullable=True),
    sa.Column('viewed', sa.Integer(), nullable=True),
    sa.Column('rating', sa.FLOAT(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('chapter_count', sa.Integer(), nullable=True),
    sa.Column('chapter_updated', sa.DateTime(), nullable=True),
    sa.Column('released', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_manga')),
    sa.UniqueConstraint('slug', name=op.f('uq_tb_manga_slug'))
    )
    op.create_table('tb_perm',
    sa.Column('slug', sa.Unicode(length=200), nullable=True),
    sa.Column('id', sa.CHAR(length=10), nullable=False),
    sa.Column('acl_principal', sa.Unicode(length=45), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_perm')),
    sa.UniqueConstraint('slug', name=op.f('uq_tb_perm_slug'))
    )
    op.create_table('tb_season',
    sa.Column('slug', sa.Unicode(length=200), nullable=True),
    sa.Column('id', sa.CHAR(length=10), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.Column('category', sa.CHAR(length=2), nullable=True),
    sa.Column('type', sa.CHAR(length=6), nullable=True),
    sa.Column('year', sa.CHAR(length=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_season')),
    sa.UniqueConstraint('slug', name=op.f('uq_tb_season_slug'))
    )
    op.create_table('tb_staff',
    sa.Column('slug', sa.Unicode(length=200), nullable=True),
    sa.Column('id', sa.CHAR(length=10), nullable=False),
    sa.Column('staff_name', sa.Unicode(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_staff')),
    sa.UniqueConstraint('slug', name=op.f('uq_tb_staff_slug'))
    )
    op.create_table('tb_usr',
    sa.Column('id', sa.CHAR(length=10), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('username', sa.Unicode(length=255), nullable=True),
    sa.Column('email', sa.Unicode(length=255), nullable=True),
    sa.Column('password', sa.Unicode(length=60), nullable=True),
    sa.Column('api_key', sa.Unicode(length=40), nullable=True),
    sa.Column('secret', sa.Unicode(length=20), nullable=True),
    sa.Column('allowed_scopes', sa.Unicode(length=256), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('invite_ct', sa.Integer(), nullable=True),
    sa.Column('invited_by', sa.Unicode(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_usr')),
    sa.UniqueConstraint('api_key', name=op.f('uq_tb_usr_api_key')),
    sa.UniqueConstraint('email', name=op.f('uq_tb_usr_email')),
    sa.UniqueConstraint('username', name=op.f('uq_tb_usr_username'))
    )
    op.create_table('activations',
    sa.Column('id', sa.CHAR(length=10), nullable=False),
    sa.Column('code', sa.Unicode(length=60), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Unicode(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['tb_usr.id'], name=op.f('fk_activations_id_tb_usr')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activations'))
    )
    op.create_table('artist_manga',
    sa.Column('manga_id', sa.CHAR(length=10), nullable=False),
    sa.Column('artis_id', sa.CHAR(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artis_id'], ['tb_artist.id'], name=op.f('fk_artist_manga_artis_id_tb_artist')),
    sa.ForeignKeyConstraint(['manga_id'], ['tb_manga.id'], name=op.f('fk_artist_manga_manga_id_tb_manga')),
    sa.PrimaryKeyConstraint('manga_id', 'artis_id', name=op.f('pk_artist_manga'))
    )
    op.create_table('author_manga',
    sa.Column('manga_id', sa.CHAR(length=10), nullable=False),
    sa.Column('author_id', sa.CHAR(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['tb_author.id'], name=op.f('fk_author_manga_author_id_tb_author')),
    sa.ForeignKeyConstraint(['manga_id'], ['tb_manga.id'], name=op.f('fk_author_manga_manga_id_tb_manga')),
    sa.PrimaryKeyConstraint('manga_id', 'author_id', name=op.f('pk_author_manga'))
    )
    op.create_table('genre_manga',
    sa.Column('manga_id', sa.CHAR(length=10), nullable=False),
    sa.Column('genre_id', sa.CHAR(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['tb_genre.id'], name=op.f('fk_genre_manga_genre_id_tb_genre')),
    sa.ForeignKeyConstraint(['manga_id'], ['tb_manga.id'], name=op.f('fk_genre_manga_manga_id_tb_manga')),
    sa.PrimaryKeyConstraint('manga_id', 'genre_id', name=op.f('pk_genre_manga'))
    )
    op.create_table('grp_perm',
    sa.Column('grp_id', sa.CHAR(length=10), nullable=False),
    sa.Column('perm_id', sa.CHAR(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grp_id'], ['tb_grp.id'], name=op.f('fk_grp_perm_grp_id_tb_grp')),
    sa.ForeignKeyConstraint(['perm_id'], ['tb_perm.id'], name=op.f('fk_grp_perm_perm_id_tb_perm')),
    sa.PrimaryKeyConstraint('grp_id', 'perm_id', name=op.f('pk_grp_perm'))
    )
    op.create_table('grp_usr',
    sa.Column('grp_id', sa.CHAR(length=10), nullable=False),
    sa.Column('usr_id', sa.CHAR(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grp_id'], ['tb_grp.id'], name=op.f('fk_grp_usr_grp_id_tb_grp')),
    sa.ForeignKeyConstraint(['usr_id'], ['tb_usr.id'], name=op.f('fk_grp_usr_usr_id_tb_usr')),
    sa.PrimaryKeyConstraint('grp_id', 'usr_id', name=op.f('pk_grp_usr'))
    )
    op.create_table('tb_chapter',
    sa.Column('slug', sa.Unicode(length=200), nullable=True),
    sa.Column('id', sa.CHAR(length=10), nullable=False),
    sa.Column('chapter_title', sa.Unicode(length=200), nullable=True),
    sa.Column('chapter_prefix_image', sa.CHAR(length=1), nullable=True),
    sa.Column('chapter_no', sa.Float(precision=1), nullable=True),
    sa.Column('chapter_vol', sa.SMALLINT(), nullable=True),
    sa.Column('chapter_updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('lang_id', sa.CHAR(length=10), nullable=True),
    sa.Column('chapter_sort', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tb_manga_id', sa.CHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['lang_id'], [u'tb_lang.id'], name=op.f('fk_tb_chapter_lang_id_tb_lang')),
    sa.ForeignKeyConstraint(['tb_manga_id'], [u'tb_manga.id'], name=op.f('fk_tb_chapter_tb_manga_id_tb_manga')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_chapter')),
    sa.UniqueConstraint('slug', name=op.f('uq_tb_chapter_slug'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_chapter')
    op.drop_table('grp_usr')
    op.drop_table('grp_perm')
    op.drop_table('genre_manga')
    op.drop_table('author_manga')
    op.drop_table('artist_manga')
    op.drop_table('activations')
    op.drop_table('tb_usr')
    op.drop_table('tb_staff')
    op.drop_table('tb_season')
    op.drop_table('tb_perm')
    op.drop_table('tb_manga')
    op.drop_table('tb_lang')
    op.drop_table('tb_grp')
    op.drop_table('tb_genre')
    op.drop_table('tb_character')
    op.drop_table('tb_author')
    op.drop_table('tb_artist')
    ### end Alembic commands ###
