"""add_viewed_chapter

Revision ID: 15c56a5615d8
Revises: 597d5724a921
Create Date: 2015-06-29 11:15:04.293166

"""

# revision identifiers, used by Alembic.
revision = '15c56a5615d8'
down_revision = '597d5724a921'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_chapter', sa.Column('viewed', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_chapter', 'viewed')
    ### end Alembic commands ###
